language: python
python:
  - "2.7"
  - "3.4"
install: "pip install -r requirements_dev.txt"
services:
  - mongodb
script:
  - nosetests --with-coverage --cover-package=flask_restframework
after_success:
  - codecov
deploy:
  provider: pypi
  user:
